spring.application.name=leavehub

spring.datasource.url=jdbc:mysql://localhost:3306/employeeleavehub
spring.datasource.username=athlantes
spring.datasource.password=Athlantes2004
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true